defaults:
  - _self_
  - task: stack_blocks

name: vgc_policy

policy:
  _target_: vgc.policy.vgc_policy.VGCPolicy
  shape_meta: ${task.shape_meta}
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_schedule: 'squaredcos_cap_v2'
    clip_sample: True
    prediction_type: 'epsilon'

  horizon: 16
  n_action_steps: 8
  n_obs_steps: 2
  num_inference_steps: 100
  obs_as_global_cond: True
  diffusion_step_embed_dim: 256
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  condition_type: "film"
  d_point: 128
  dino_model_name: 'dinov2_vits14'

ema:
  _target_: diffusion_policy_3d.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 4
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 4
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  lr_scheduler: "cosine"
  lr_warmup_steps: 500
  num_epochs: 100
  gradient_accumulate_every: 1
  use_ema: True
  rollout_every: 50
  checkpoint_every: 10
  val_every: 10
  sample_every: 10
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  group: ${name}
  id: null
  mode: online
  name: ${now:%H.%M.%S}_${name}_${task.name}
  project: vgc_policy
  resume: true
  tags:
  - vgc

checkpoint:
  save_ckpt: True
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%H.%M.%S}_${name}_${task.name}
  sweep:
    dir: data/outputs/${now:%H.%M.%S}_${name}_${task.name}
    subdir: ${hydra.job.num}



