defaults:
  - _self_
  - task: stack_blocks

name: vgc_policy

policy:
  _target_: vgc.policy.vgc_policy.VGCPolicy
  shape_meta: ${task.shape_meta}
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_schedule: 'squaredcos_cap_v2'
    clip_sample: True
    prediction_type: 'epsilon'

  horizon: 16
  n_action_steps: 8
  n_obs_steps: 2
  num_inference_steps: 100
  obs_as_global_cond: True
  diffusion_step_embed_dim: 256
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  condition_type: "film"
  d_point: 128
  dino_model_name: 'dinov2_vits14'

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  lr: 1e-4
  weight_decay: 1e-6
  lr_scheduler: "cosine"
  lr_warmup_steps: 500
  num_epochs: 100
  gradient_accumulate_every: 1
  use_ema: True
  checkpoint_every: 10
  val_every: 10
  sample_every: 10
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

dataloader:
  batch_size: 4
  num_workers: 4
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 4
  num_workers: 4
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: ${training.lr}
  weight_decay: ${training.weight_decay}
  betas: [0.95, 0.999]
  eps: 1.0e-08
