name: beat_block_hammer

dataset:
  _target_: vgc.dataset.vgc_dataset.VGCDataset
  zarr_path: data/beat_block_hammer-demo_3d_vision_easy-100-ppi.zarr
  horizon: ${policy.horizon}
  pad_before: 1
  pad_after: 7
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null

shape_meta:
  action:
    shape: [14]
  obs:
    agent_pos:
      shape: [32]
    point_cloud:
      shape: [1024, 6]
    images:
      shape: [2, 3, 224, 224]

env_runner:
  _target_: diffusion_policy_3d.env_runner.robot_runner.RobotRunner
  max_steps: 300
  n_obs_steps: ${policy.n_obs_steps}
  n_action_steps: ${policy.n_action_steps}
  task_name: ${name}
