name: stack_blocks

dataset:
  _target_: vgc.dataset.vgc_dataset.VGCDataset
  zarr_path: data/stack_blocks_two-demo_3d_vision_easy-100-ppi.zarr
  horizon: ${policy.horizon}
  pad_before: 1
  pad_after: 7
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null

shape_meta:
  action:
    shape: [14]
  obs:
    agent_pos:
      shape: [32]
    point_cloud:
      shape: [1024, 6]
    images:
      shape: [2, 3, 224, 224]
